### ISSUE TITLE
XCB support

### ISSUE THREAD

**Issue by Ralith** [rust-windowing/raw-window-handle#11]
The current implementation treats X11 as a monolith. Per Vulkan convention, the X11 case should probably be renamed Xlib, and an Xcb case added.

**Comment by msiglreith** [comment]
I'm currently in the process of porting ash-window towards 0.2 (XCB and Android support 👍).
While splitting X11 into Xlib and Xcb I noticed that the XcbHandle has a [`surface`](https://docs.rs/raw-window-handle/0.2.0/raw_window_handle/unix/struct.XcbHandle.html#fields), which seems kind of an odd naming as there doesn't seem to be an actual surface type in the xcb api. Vulkan uses the term `window` with type `xcb_window_t` and I believe raw-window-handle assumes takes same thing here.

**Comment by Osspial** [comment]
Hmm. Honestly, I'm not too happy about that, but I should've reviewed the PR more thoroughly. Sorry about that.
