### ISSUE TITLE
Combine the X11 window handles into one type

### ISSUE THREAD

**Issue by notgull** [rust-windowing/raw-window-handle#121]
Windows in X11 are defined as "XIDs", which are unique 32-bit IDs. However, there are separate types in this crate for Xlib and XCB window handles, despite the fact that, fundamentally, they refer to the same thing.

```rust
pub struct XlibWindowHandle {
    /// An Xlib `Window`.
    pub window: c_ulong,
    /// An Xlib visual ID, or 0 if unknown.
    pub visual_id: c_ulong,
}

pub struct XcbWindowHandle {
    /// An X11 `xcb_window_t`.
    pub window: u32, // Based on xproto.h
    /// An X11 `xcb_visualid_t`, or 0 if unknown.
    pub visual_id: u32,
}
```

Xlib uses `c_ulong` because of an extremely characteristic poor design decision, XCB gets this right. At the next breaking change, it would be nice to combine them into one type to remove any ambiguity.

**Comment by kchibisov** [comment]
They must be separate because the extensions using them are different, thus you must distinguish them somehow.

**Comment by notgull** [comment]
I see, thanks for clarifying!
