### ISSUE TITLE
`v0.6` release planning

### ISSUE THREAD

**Issue by madsmtm** [rust-windowing/raw-window-handle#125]
What do we need to fix before the next major release?

There are requests for us doing the server trick again, which I'll be up for (trying to do), so mostly opening this issue to keep track of that.

**Comment by notgull** [comment]
I wanted to get rid of the `Active` type since we're doing a breaking change anyways.

**Comment by notgull** [comment]
> I wanted to get rid of the `Active` type since we're doing a breaking change anyways.

Did this in #126. Anything else that we need to think about?

**Comment by madsmtm** [comment]
Hmm, I think the blanket implementations for `&T` and so on are going to be a problem for us, since we effectively want to do a blanket impl for `T: new::HasWindowHandle`.

Still considering this, but perhaps we could do the opposite? Something like `T: old::HasWindowHandle`, and then prepare for v7 where it would not be a problem?

Otherwise, we'll have to encourage either producer crates or consumer crates to support v5 for at least a release cycle or two.

**Comment by madsmtm** [comment]
Extra possibility: We could consider removing the blanket impls in v6, to allow v7 to properly use the semver trick again.

**Comment by madsmtm** [comment]
Blocked by (at least discussion of):
- [ ] https://github.com/rust-windowing/raw-window-handle/pull/136
- [ ] https://github.com/rust-windowing/raw-window-handle/issues/135

**Comment by madsmtm** [comment]
v0.6 has been released
