### ISSUE TITLE
Should X display/connection handles be nullable?

### ISSUE THREAD

**Issue by madsmtm** [rust-windowing/raw-window-handle#141]
`XlibDisplayHandle.display` and `XcbDisplayHandle.connection` are nullable; should they be?

Previously discussed in https://github.com/rust-windowing/raw-window-handle/pull/136.

**Comment by notgull** [comment]
If I remember correctly, display handles can be null for EGL. I've changed my mind since my posts in #136, I think allowing this use case is worth it.

**Comment by kchibisov** [comment]
Yes, there's a thing called `EGL_DEFAULT_DISPLAY`, so it'll use the display somehow automatically. Also it does open connection under the hood with xcb iirc the mesa code.

**Comment by i509VCB** [comment]
Whether null is correct depends on the context. Like kchibisov, for EGL it is valid. Meanwhile in Vulkan, you must provide a valid pointer to a display.

**Comment by notgull** [comment]
Closing now, as I think this question was answered.
