### ISSUE TITLE
Proposal: Remove `Copy` from `RawDisplayHandle`

### ISSUE THREAD

**Issue by madsmtm** [rust-windowing/raw-window-handle#142]
Should we do this?

Similar to https://github.com/rust-windowing/raw-window-handle/issues/138, but more for consistency this time, it confused me that display handles are `Copy` while window handles are not.

**Comment by madsmtm** [comment]
Actually, maybe we should make _all_ the raw handles `!Copy`?

**Comment by notgull** [comment]
I am in favor of this

**Comment by kchibisov** [comment]
Making it non copy is more forward compat if the handle will have complicated semantics under the hood.
