### ISSUE TITLE
Proposal: Make the error type implementor-selectable?

### ISSUE THREAD

**Issue by madsmtm** [rust-windowing/raw-window-handle#143]
Instead of defining the allowed errors returnable by the window handle traits, maybe we should make it an associated type `Error` instead, similar to e.g. [`TryFrom::Error`](https://doc.rust-lang.org/nightly/std/convert/trait.TryFrom.html#associatedtype.Error)? Then libraries that never return an error could make that be `Infallible`.

**Comment by notgull** [comment]
This would make the trait not object safe, which I would be skeptical about. Especially since most current implementors of the traits should be providing errors, just in case.

**Comment by madsmtm** [comment]
Right, conflicts with object safety too, and you do make some fair points
