### ISSUE TITLE
Add tests for Rust subleties

### ISSUE THREAD

**Issue by madsmtm** [rust-windowing/raw-window-handle#147]
There are many small ways to break certain semver guarantees, and it would be nice if we could avoid making these mistakes; so let's add some tests to ensure that!

Add tests for:
- [ ] Presence (or absence) of marker traits on types:
  - `Send`
  - `Sync`
  - `UnwindSafe`
  - `RefUnwindSafe`
  - `Unpin`
- [x] ~Contains interior mutability (e.g. disallowing placing something in a static)~
- [ ] Object safety on the traits we expose.
- [x] Variance of any lifetimes and/or generics we expose.

Possibly also: Integrate [`cargo-semver-checks`](https://github.com/obi1kenobi/cargo-semver-checks) in CI?

**Comment by Lokathor** [comment]
I run cargo-semver-checks on an actual publish but putting it in CI in some way is reasonable as well

**Comment by kchibisov** [comment]
You could do doc tests for all of that like glutin does for example, we test `Send`/`Sync` and `!Send`/`!Sync` there to ensure semantics across the backends.
