### ISSUE TITLE
Can we remove most of the conditional compilation stuff?

### ISSUE THREAD

**Issue by Lokathor** [rust-windowing/raw-window-handle#16]
The conditional compilation stuff is an unnecessary complication to the system.

Basically, every library that _consumes_ a `HasRawWindowHandle` value already needs to have a default, catch-all case where they get some unknown handle type and then error out. We even want the enum to be tagged as non-exhaustive so that the library can be "future proof" and force people to have a default cause so that we don't break semver when new window systems are eventually added.

So since your consuming code's match statement already needs to say
```rust
  unknown => return Err(format!("unknown window handle type: {:?}", unknown)),
```
at the end of it, then having the IOS handle conditionally compiled to not exist on windows doesn't actually add anything. Either way you can't have exhaustive matching.

And since we're just giving all of our handle definitions in terms of libc types and `core::ffi::c_void` and so forth there's not really a problem with pulling in all sorts of platform dependencies if we just have every variant compiled in on all platforms.

So I think that never doing any conditional compilation is probably better in the long term. Makes things simpler to reason about.

**Comment by hecrj** [comment]
Have we considered removing the unexhaustive `RawWindowHandle` enum and `HasRawWindowHandle` trait altogether and adding platform-specific traits instead?

What is the purpose of giving up guarantees by wrapping the handle in an unexhaustive enum when our users have to implement platform-specific code anyway?

**Comment by Lokathor** [comment]
No the point is that an _end user_ of this communication point sees it as just one thing 

```rust
let surface = instance.make_surface_for_window(&window).unwrap();
```

Since some systems potentially have more than one window system available, for this to move all the complexity away from the end user there cannot be window specific methods.

**Comment by hecrj** [comment]
@Lokathor The same way we currently [force our users to pattern match using conditional compilation](https://github.com/gfx-rs/wgpu/blob/master/wgpu-native/src/instance.rs#L99), we can force them to declare a function using conditional compilation too ([they probably have to do this anyway](https://github.com/gfx-rs/wgpu/blob/master/wgpu-native/src/instance.rs#L147)):

```rust
#[cfg(target_os = "ios")]
fn make_surface_for_window<W: HasIOSHandle>(&self, window: &W) -> Result<Surface, Error> {
    // window.ui_window()
    // window.ui_view()
    // ...
}
```

The main difference is that there won't be any need for non-exhaustive variants or fields, and there won't be misleading APIs taking an unsupported window handle and erroring at runtime.

**Comment by Lokathor** [comment]
No, graphics libs aren't the end users. Graphics libs and window libs can both have a hard time and I don't much care because you sort it out a few times and then it's done.

I mean _actual_ end users that want to make a window and then tell a backend to work on that window. That is the situation that will be written out over and over in countless new projects and demos, and that's the case that we want to optimize simplicity for.

**Comment by hecrj** [comment]
@Lokathor I don't think my proposal would affect end users.

In fact, I think it would help them. With my approach, if our _end users_ try to compile a graphics library on an unsupported platform, they will get a compilation error, instead of a runtime error.

**Comment by hecrj** [comment]
@Osspial What about exposing `HasRawWindowHandle` as the end-user-facing trait, conditionally extending a platform-specific trait?

```rust
#[cfg(target_os = "linux")]
pub trait HasRawWindowHandle: crate::unix::HasUnixHandle {}

#[cfg(target_os = "windows")]
pub trait HasRawWindowHandle: crate::windows::HasWindowsHandle {}
```

Graphics libraries could then write a single function:

```rust
impl Instance {
    pub fn create_surface<W: HasRawWindowHandle>(&mut self, window: &W) -> Result<Surface, Error> {
        #[cfg(target_os = "linux")]
        let surface = self.create_surface_for_unix(window)?;

        #[cfg(target_os = "windows")]
        let surface = self.create_surface_for_windows(window)?;

        // ...

        Ok(surface)
    }
}
```

Would this work? This is very similar to [what `wgpu-natve` is already doing](https://github.com/gfx-rs/wgpu/blob/87b61d206c0e984c960fd49fb5bd7b9a6ab49331/wgpu-native/src/instance.rs#L99), but it will fail at compile-time on an unsupported platform. Additionally, traits are more flexible than enums and structs when trying to avoid breaking changes.

**Comment by Osspial** [comment]
Closing this issue, since there doesn't seem to be a compelling reason to do this and the discussion in this issue has moved to a different topic. We can continue discussion of the trait prototype in #23.
