### ISSUE TITLE
Consider exposing C API

### ISSUE THREAD

**Issue by kvark** [rust-windowing/raw-window-handle#24]
For libraries that have C APIs, like wgpu-native or gfx-portability, it would be great if we could *also* use raw window handle stuff from C. That would allow us to drop all the platform-specific WSI functions from the public API and leave only one that could be universally used by GLFW, SDL, Winit, and other clients. Currently, we can use a single API point from Rust, but not from C.

**Comment by Lokathor** [comment]
Well, you're the client. What do you think the API actually looks like from a C perspective?

Right now, 0% of the crate is compatible with C.

**Comment by kvark** [comment]
It's straightforward to wrap raw-window-handle in a C API. Question is more in line of whether this repository should be the home to such wrapper.

**Comment by kvark** [comment]
Anyhow, I haven't fleshed out the details here. Going to close this for now and give it more thought.

**Comment by Osspial** [comment]
I would support adding a C API to this crate.
