### ISSUE TITLE
Increase project scope?

### ISSUE THREAD

**Issue by Didgy74** [rust-windowing/raw-window-handle#25]
Issue #5 proposed to add OpenGL support which is, strictly speaking, outside the current scope of `raw-window-handle` where you only can grab the raw C handles from a windowing system, and that's it.

If there is a consensus to expand the project by adding OpenGL interop functionality, I think a change in scope is in order. Changing the name of the crate to something like `gfx-wsi-interop` would allow us to implement any functionality (including Vulkan, Metal) that makes interop between the systems both backend-agnostic and simple.

**Comment by Osspial** [comment]
I'd rather not expand the scope of this project any further. I laid out my reasoning in https://github.com/rust-windowing/raw-window-handle/issues/5#issuecomment-528052388, but I can expand on that if necessary.

**Comment by Didgy74** [comment]
No need to elaborate. Issue closed.
