### ISSUE TITLE
Prefer `core::ffi::c_void` type over `libc::c_void`

### ISSUE THREAD

**Issue by Lokathor** [rust-windowing/raw-window-handle#3]
All `c_void` are in some sense similar since you can always just cast between them, however, since core offers a `c_void` type we should at least use that common point of communication as much as possible.

**Comment by Osspial** [comment]
I'm not opposed to doing this, but it's worth noting that we'll still have to pull in `libc` to maintain `no_std` compatibility on Linux, since X11 uses a `c_ulong` to represent the window handle.
