### ISSUE TITLE
Additional Licenses

### ISSUE THREAD

**Issue by Lokathor** [rust-windowing/raw-window-handle#41]
It's traditional for core Rust projects to be MIT OR Apache-2.0. Personally I also like to see the Zlib license as an option as well.

Could we get additional license options for Apache-2.0 at least, and possibly Zlib as well?

This would need a sign off from all those who have added code (I'll list them here _without_ pings and we can ping them if people generally agree with this issue at all).

* Osspial (lead)
* LeshaInc marked stuff as "derive Hash" but I don't think that's significant.
* aloucks similarly put the initial derives on the enum
* dxenonb added readme stuff but not code
* msiglreith renamed a field and added some docs lines
* repi helped fix the last license thing actually, but no code changes.
* ryanisaacg added the web handle
* Didgy74 added XCB and Android.

**Comment by Osspial** [comment]
AFAIK the main reason for Rust projects to be dual-licensed under the MIT and Apache licenses is that the Apache license isn't compatible with the GPL-2.0. I see no reason to go through the effort of multi-licensing when the MIT license is compatible with basically everything.

**Comment by solarane** [comment]
+1. Esp. zlib would definitely be a useful addition.
