### ISSUE TITLE
u32 vs u64 compile error on arm/raspberry pi 4b

### ISSUE THREAD

**Issue by MarkSwanson** [rust-windowing/raw-window-handle#45]
I'm unable to compile wgpu-rs, and it looks like the problem is is in raw-window-handle.
wgpu is hard-coded to use a u64 for window, but raw-window-handle defines window as a c_ulong:

pub struct XlibHandle {
    /// An Xlib `Window`.
    pub window: c_ulong,
...

It seems like c_ulong should really c_ulonglong.

The wgpu error:

error[E0308]: mismatched types
  --> wgpu-native/src/device.rs:85:9
   |
85 |         window,
   |         ^^^^^^ expected u32, found u64
   |
help: you can convert an `u64` to `u32` and panic if the converted value wouldn't fit
   |
85 |         window: window.try_into().unwrap(),
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

**Comment by MarkSwanson** [comment]
Hmm, after thinking about it perhaps c_ulong is correct, and the real bug is in wgpu. wgpu should be using usize instead of u64.

**Comment by Osspial** [comment]
I can confirm that this is an issue in wgpu. Looking at `X.h`, `Window` is a typedef-ed `XID`, and `XID` is a typedef-ed `unsigned long`:

```c
#ifndef _XSERVER64
#  ifndef _XTYPEDEF_XID
#    define _XTYPEDEF_XID
typedef unsigned long XID;
#  endif
#  ifndef _XTYPEDEF_MASK
#    define _XTYPEDEF_MASK
typedef unsigned long Mask;
#  endif
#  ifndef _XTYPEDEF_ATOM
#    define _XTYPEDEF_ATOM
typedef unsigned long Atom;		/* Also in Xdefs.h */
#  endif
typedef unsigned long VisualID;
typedef unsigned long Time;
#else
#  include <X11/Xmd.h>
#  ifndef _XTYPEDEF_XID
#    define _XTYPEDEF_XID
typedef CARD32 XID;
#  endif
#  ifndef _XTYPEDEF_MASK
#    define _XTYPEDEF_MASK
typedef CARD32 Mask;
#  endif
#  ifndef _XTYPEDEF_ATOM
#    define _XTYPEDEF_ATOM
typedef CARD32 Atom;
#  endif
typedef CARD32 VisualID;
typedef CARD32 Time;
#endif

typedef XID Window;
```

With that in mind, I'm going to close this issue.
