### ISSUE TITLE
unsigned long compile error on 32-bit systems

### ISSUE THREAD

**Issue by MarkSwanson** [rust-windowing/raw-window-handle#46]
After looking into issue 45 in more detail
ref: https://github.com/rust-windowing/raw-window-handle/issues/45

I believe the bug is indeed in raw-window-handle.
I also believe that the best place to fix this is in raw-window-handle.

Here's the flow:
raw-window-handle defines Window as u64. Note that c_ulong is mapped to a u64 via:
crate libc-0.2.66/src/unix/linux_like/linux/gnu/b64/x86_64/not_x32.rs

So wgpu can't use the correct 'usize' - raw-window-handle forces u64 if wgpu wants to successfully compile on 64-bit ubuntu.
But of course if wgpu uses u64 to compile successfully on 64-bit ubuntu, it will fail to compile on 32-bit armv7l.

The root cause of this problem seems to be the libc crate's definition of u_long maps to u64 - in a perfect world it would map to usize.

However, it seems that the libc folks new better but wanted this behavior anyway. They've been very careful about usize/isize issues. From reading libc crate issues around usize I'm now more sure that this is the desired/intended behavior. I don't believe we can use c_ulong for the xlib window.

Would the raw-window-handle folks be open to a PR changing:
pub struct XlibHandle {
    /// An Xlib `Window`.
    pub window: c_ulong,

to this?

pub struct XlibHandle {
    /// An Xlib `Window`.
    pub window: usize,

Thanks!

**Comment by Osspial** [comment]
`c_ulong` is defined as `u32` on 32-bit Linux systems: https://docs.rs/libc/0.2.66/i686-unknown-linux-gnu/libc/type.c_ulong.html. Additionally, the [X11 crate](https://docs.rs/x11-dl/2.18.4/i686-unknown-linux-gnu/x11_dl/xlib/type.XID.html) defines `XID` (and, by proxy, `XWindow`) as a `c_ulong`. Why not update wgpu to use `c_ulong` instead of `usize`?

**Comment by MarkSwanson** [comment]
I did that and it works fine. Thanks.
