### ISSUE TITLE
Implement HasRawWindowHandle for RawWindowHandle

### ISSUE THREAD

**Issue by kvark** [rust-windowing/raw-window-handle#49]
Currently, there is only one way to go from `winit::Window` to `RawWindowHandle`. Once you get a raw window handle, everything at the lower level has to work with it directly. This is an unfortunate limitation.

For example, [gfx-backend-vulkan::Instance::create_surface](https://docs.rs/gfx-backend-vulkan/0.5.6/gfx_backend_vulkan/struct.Instance.html#method.create_surface) expects `HasRawWindowHandle`. That means we can't get `RawWindowHandle` at any layer above it, but sometimes we really want that, e.g. when we construct `RawWindowHandle` manually on the client side.

**Comment by msiglreith** [comment]
Similar issue: https://github.com/norse-rs/ash-window/pull/10

**Comment by Osspial** [comment]
This was actually implemented at one point (see #29), but it turned out to be unsound so it had to be reverted (see #35). I'd be down with adding a read-only, unsafe-to-construct `RawWindowHandle` wrapper that implements `HasRawWindowHandle` to circumvent that, though.
