### ISSUE TITLE
Could not retrieve any SDL2 window info

### ISSUE THREAD

**Issue by vivax3794** [rust-windowing/raw-window-handle#56]
so I got sent here by a error ...... 
```
thread 'main' panicked at 'Could not retrieve any SDL2 window info, and Osspial wrote the trait to be infallible despite that clearly not always being the case, so now you got this panic. htt
ps://github.com/rust-windowing/raw-window-handle/issues/new', /home/vivax/.cargo/registry/src/github.com-1ecc6299db9ec823/beryllium-0.3.2/src/window/raw_window.rs:107:7
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Lokathor** [comment]
hi, i wrote that message.

If you're still interested in this, could you give more details about what platform you're on?

I can't say I recognize your username, and I'm quite shocked that anyone but me is using beryllium

**Comment by tato** [comment]
@Lokathor 

I also found the same panic. Running the 'minimal-sdl2' example from https://github.com/parasyte/pixels on Ubuntu 20.04. 😃

**Comment by Lokathor** [comment]
I guess one thing it could do is to just pass all null pointers if system window info can't be obtained.

It's not great, it mostly just pushes the panic elsewhere probably (the consumer of the info probably can't cope with a lack of info).

**Comment by notgull** [comment]
Closing this issue as it is no longer possible to invoke in `raw-window-handle`, and as of #122 it should be possible to turn this panic into a normal error.
