### ISSUE TITLE
UWP CoreWindow variant

### ISSUE THREAD

**Issue by kvark** [rust-windowing/raw-window-handle#57]
Apparently, this is what one uses to render DX12 in UWP: https://docs.microsoft.com/en-us/uwp/api/windows.ui.core.corewindow?view=winrt-19041
See also - https://github.com/msiglreith/rostkatze/wiki/RKZ-extensions
cc @msiglreith

**Comment by msiglreith** [comment]
PR: https://github.com/rust-windowing/raw-window-handle/pull/68

**Comment by Lokathor** [comment]
Sorry i forgot that PR, merged it.
