### ISSUE TITLE
New release? 

### ISSUE THREAD

**Issue by kettle11** [rust-windowing/raw-window-handle#58]
It's been almost a year since the last release and I've been looking forward to using the version of `raw-window-handle` that doesn't depend on `libc`. Is there any chance of a new release soon?

**Comment by msiglreith** [comment]
Hi, I feel that there a bunch of open topics for this library, but currently missing a maintainer to decide and take care of it.
As this is such a core piece to the ecosystem more hands involved would be awesome - we rely too much on Osspial doing great stuff ❤️

**Comment by Lokathor** [comment]
I just took over, but I'll try to get a new release "very soon".

I haven't looked too closely at the library since like 0.1 or 0.2, so I want to orient myself a bit first.
