### ISSUE TITLE
Use separate types for each platform

### ISSUE THREAD

**Issue by chrisduerr** [rust-windowing/raw-window-handle#60]
I find the current API a bit strange, since it basically offers an enum that just has a single member on most platforms.

Is there any reason why the `RawWindowHandle` isn't just a platform-specific `type` that is decided at compile-time? It's not like people are going to be matching against the platform's implementation at runtime, especially since this is impossible because the enum has only the members available for the current platform.

**Comment by grovesNL** [comment]
The variants don't all match 1:1 with a platform, so the variant isn't known at compile-time. For example, [Xlib, Xcb, and Wayland are all available on `linux`](https://github.com/rust-windowing/raw-window-handle/blob/master/src/lib.rs#L108-L172)

**Comment by chrisduerr** [comment]
Yeah, which is not a problem. You can still provide an enum for platforms that actually make a decision at runtime.

But adding a runtime check for something that can be uniquely identified at compile time just leads to unergonomic code.

**Comment by Lokathor** [comment]
I'm inclined to go in the direction of https://github.com/rust-windowing/raw-window-handle/issues/63. We keep the enum, and just remove all the cfg stuff.
