### ISSUE TITLE
Publish version 0.4 on crates.io

### ISSUE THREAD

**Issue by leafjolt** [rust-windowing/raw-window-handle#72]
Since #70 was merged,  I was wondering if there is anything left to do before releasing version 0.4 on crates.io, or if the release can go forward.

**Comment by maroider** [comment]
I think we're still blocked on reaching consensus in #71.

**Comment by leafjolt** [comment]
Would it be possible to release a new version that leaves out the safety changes/TrustedWindowHandle for now while #71 is sorted out but includes the changes to platform elements, such as removing cfg guards, changing `IOS` to `UiKit` (and other similar changes) and adding Redox/WinRt support? I think that the platform changes are still somewhat significant and would be useful to many users.

**Comment by maroider** [comment]
I believe it is feasible to do so.

cc @Lokathor

**Comment by Lokathor** [comment]
If no one's opposed I can probably get to this on Monday or Tuesday.

**Comment by Lokathor** [comment]
published! https://docs.rs/raw-window-handle/0.4.0/raw_window_handle/index.html

**Comment by maroider** [comment]
Errrm, did you miss this part?

> Would it be possible to release a new version that **leaves out the safety changes/TrustedWindowHandle for now while #71 is sorted out**

**Comment by Lokathor** [comment]
i thought that those were *already* "out" and so i could just publish the `main` branch.

**Comment by Lokathor** [comment]
Okay I yanked 0.4.0, sorry for the confusion.

So... what would a PR that makes the crate better for wgpu look like. I've never used wgpu ever so maybe I don't get what's "going stale". @maroider can you do a PR for whatever you need changed.

**Comment by madsmtm** [comment]
I think this can be closed.

On a related note, I've opened #74 to alleviate the need for ecosystem-wide upgrade.
