### ISSUE TITLE
Make `HasRawWindowHandle for &T` allow for T: ?Sized

### ISSUE THREAD

**Issue by Lokathor** [rust-windowing/raw-window-handle#76]
This would be a very small break, so it has to be in the next breaking release.

**Comment by aloucks** [comment]
I think Rust has had small breaking changes in patch releases that happened almost immediately after minor release (after a bug was found, although I can't find the example). Considering that those `impl`s were added in `0.4.1` and it was released only a few days ago, it might be worth it to just make this change now and release `0.4.2`.

**Comment by Lokathor** [comment]
Alright, i think it's fine, can you do that PR? I'll have some time for Rust stuff tomorrow and i'll try to fix this and the semver trick at the same time.
