### ISSUE TITLE
Decouple display and window handles

### ISSUE THREAD

**Issue by kchibisov** [rust-windowing/raw-window-handle#92]
When user wants to deal with platform specific code they most of the time need raw display, like e.g. wl_display. However RawWindowHandle provides with both of them.

I'd suggest to logically split them into `RawDisplayHandle` and `RawWindowHandle`, where `RawDisplayHandle` would have only reference to display and `RawWindowHandle` could have only window, like `wl_surface` or be the way it is right now?

The issue I'm having is that I want Display on every platform, but I don't want surface, since the surface isn't yet created.

For example winit could implement `raw_display_handle` on event loop, so I can pass to e.g. glutin.

**Comment by maroider** [comment]
From what I understand, this would make sense for `WaylandHandle.display`, `XcbHandle.connection`, and `XlibHandle.connection`? I'm not sure if there's something analogous on other platforms.

**Comment by kchibisov** [comment]
For something like android/macOS it would make sense to have plain `Android` and `Macos`, etc. Since on those platforms you don't have those. Also with `Gbm(device)`.

So it'll work the same way it works right now, it just prevent me from creating `RawDisplay` right inside `glutin`.

**Comment by maroider** [comment]
> So it'll work the same way it works right now, it just prevent me from creating `RawDisplay` right inside `glutin`.

Alright. I'm not familiar enough with `glutin` to understand why this would be useful, but I'm assuming this has something to do with decoupling `glutin` from `winit`?

**Comment by kchibisov** [comment]
>Alright. I'm not familiar enough with glutin to understand why this would be useful, but I'm assuming this has something to do with decoupling glutin from winit?

To create EGLDisplay or GLXDisplay you need raw display handle, nothing more. This display allows you to create objects, such as EGLContext, EGLConfig, EGLSurface, etc. The RawWindowHandle is only required for EGLSurface, and not all the surfaces actually, since e.g. PBuffers don't need it at all.

I'd assume the same applies to vulkan or e.g. softbuffer(not the current impl of softbuffer in particular).

**Comment by MarijnS95** [comment]
> I'd assume the same applies to vulkan

I don't recall there being any concept of a "Display" connection (needed) to do this. As long as you can enumerate a Vulkan device one can create/allocate a texture for "rendertarget" purposes.

You'll need both to create a surface _on a window_ though:

https://github.com/ash-rs/ash/blob/master/ash-window/src/lib.rs

Perhaps a "display" handle may be relevant for `VK_EXT_physical_device_drm` to associate a physical Vulkan device with its DRM handle.

**Comment by kchibisov** [comment]
Well, don't you need a wl_display for Wayland platform with vulkan? I'd assume you'd need one.

**Comment by MarijnS95** [comment]
@kchibisov I don't think you need any of that to create a Vulkan device and do anything like compute or offscreen rendering. As linked to the `ash-window` crate a `wl_display` _and_ `wl_surface` are needed to create a `vkSurfaceKHR` though.

**Comment by kchibisov** [comment]
That's interesting. Though for EGL you need wl_display to create EGLDisplay, and the wl_surface is required to for `EGLCreatePlatformWindow` (but not `wl_display`, since `EGLDisplay` is used here).

In general `wl_display` could be used to initialize stuff that doesn't require window, like setting up a wayland queue to handle events.

**Comment by MarijnS95** [comment]
@kchibisov Yes that surprised me too, seems the EGL API builds on top of an active windowing system (but it should be possible to run it headless?) whereas Vulkan only looks at physical GPUs provided by the system and can access them without any.

I do agree that it'd be nice to have/use it this way.

**Comment by kchibisov** [comment]
>This entire topic completely doesn't make sense to me as a Win32 programmer because with Win32 it's just the HWND and that's it.

Yeah, because you have only one possible display server? On macOS and android it's the same from what I can see, however Wayland, X11, and XCB do have their own stuff to connect to system display server, since you know, there're multiple of them (mesa should work with Xorg and Wayland at the same time, and it must differ them somehow). So something like `RawDisplay` will be required for glutin shorty ( I already have one internally, so I can upstream it later on when I'll be done with the rest platforms).

**Comment by MarijnS95** [comment]
@Lokathor Doesn't Windows have this for `HINSTANCE` (used in `ash-window`) as well? It's been super long ago but I thought that was application/process/message-pump wide?

**Comment by Lokathor** [comment]
If a "display server" is something like "the system has multiple display servers available, and i get to pick what display server i want to make a window for", that doesn't really map to any windows API that I know about.

Like kchibisov said, there's just the one windowing system on Windows, and you get what you get.

**Comment by MarijnS95** [comment]
@Lokathor Thanks for the detailed insight!

So yes, if @kchibisov has a use-case for needing the display-server connection without having a surface/window yet - even if it's just for EGL - I think this is a good change to make. And Vulkan user _may_ benefit when utilizing [`VK_EXT_physical_device_drm`](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_EXT_physical_device_drm.html).

**Comment by notgull** [comment]
I am a fan of this, especially for cases where the display isn't easily clonable. My only concern: how would you stop, say, a Wayland display server from being used with, say, an XCB window? That feels like a larger surface that could possibly panic.

**Comment by kchibisov** [comment]
>My only concern: how would you stop, say, a Wayland display server from being used with, say, an XCB window? That feels like a larger surface that could possibly panic.

Well the API can prevent it in a first place. And if you've got a Wayland display, you're unlikely to get an Xcb window, since you don't have xcb around?

The Api is already unsafe to begin with, since you basically pass pointers around. In general applications can compare whether the right thing is passed. Like it's not a problem when we're doing low level stuff.

The main issue I'm trying to solve here, is that I need a display before I even try to create a surface, like I don't have a window at all in glutin when I query for X11 visuals with glx for example. And later on I'll use that visual to create an X11 window :/

If you have an idea on how to make them safer to use, I'm all years, but take into account that I should have display without a window.
